version: '3.7'

services:

  whizmo-backoffice-prod:
    container_name: whizmo-backoffice-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '5000:80'
    environment:
      - "REACT_APP_API_BASE_URL=http://192.168.35.92:10900/api"
    