version: '3.7'

services:

  whizmo-backoffice:
    container_name: whizmo-backoffice
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    expose:
      - "3000"
    environment:
      - NODE_ENV=development