version: '3.7'

services:

  realestate-kasaz-prod:
    container_name: realestate-kasaz-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '5000:80'
    environment:
      - "REACT_APP_API_BASE_URL=http://localhost:3000/graphql"
    