version: '3.7'

services:

  realestate-kasaz:
    container_name: realestate-kasaz
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
    expose:
      - "8080"
    environment:
      - NODE_ENV=development